CREATE TABLE IF NOT EXISTS scores (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 org TEXT NOT NULL,
 score INTEGER NOT NULL DEFAULT 0,
 updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(name, org)
);
CREATE INDEX IF NOT EXISTS idx_scores_score ON scores(score DESC);
